# Generated by Django 2.0.7 on 2018-07-25 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180725_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0),
        ),
        migrations.AddField(
            model_name='planner',
            name='type',
            field=models.CharField(default='U\\A', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='expcted_cpacity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(999999999)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='pud_date',
            field=models.DateTimeField(verbose_name='Publish Date'),
        ),
        migrations.AlterField(
            model_name='planner',
            name='mobile',
            field=models.CharField(max_length=13),
        ),
    ]
