# Generated by Django 2.0.7 on 2018-07-25 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180725_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='planner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Planner'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Sent'), (1, 'Offered'), (2, 'Accepted'), (3, 'Rejected')], null=True),
        ),
        migrations.AlterField(
            model_name='planner',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
