# Generated by Django 2.0.7 on 2018-08-09 12:22

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_planner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(default='logo/logo.png', upload_to='logo'),
        ),
    ]
