# Generated by Django 2.1 on 2018-08-09 21:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_planner_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(default='events/img/profile/logo.jpg', upload_to='logo'),
        ),
    ]
